# directivas top-level (pid, logs)

pid /tmp/nginx-lab.pid;
error_log /tmp/nginx-lab-error.log;

events { }

http {
    log_format edge '$remote_addr "$request" $status '
	    'request_time=$request_time '
	    'upstream_time=$upstream_response_time';
	proxy_connect_timeout 5s;
	proxy_send_timeout 10s;
	proxy_read_timeout 10s;
    access_log /tmp/nginx-lab-access.log edge;

    upstream  backend {       # requerido #6
    	server localhost:8080;
	keepalive 16;
    }
    
    server {
    	listen 8081;             # requerido #1

	location / {       # requerido #2
		proxy_pass http://localhost:3000;
	}
    	location /api/ {    # requeridos #3, #4, #5, #6
    		proxy_pass http://backend;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Host $host;
		proxy_connect_timeout 5s;
		proxy_send_timeout 10s;
		proxy_read_timeout 10s;
		proxy_http_version 1.1;
		proxy_set_header Connection "";

	}
    }
}
